#!/bin/bash

echo "🔧 Fix pentru minikube tunnel"
echo ""
echo "Problema: Portul 80 nu este accesibil"
echo ""
echo "Soluții:"
echo ""
echo "1. Oprește tunnel-ul actual (Ctrl+C în terminalul unde rulează)"
echo ""
echo "2. Repornește tunnel-ul cu sudo:"
echo "   sudo minikube tunnel"
echo ""
echo "3. SAU folosește port-forward direct (fără tunnel):"
echo "   kubectl port-forward -n ingress-nginx svc/ingress-nginx-controller 8080:80"
echo "   Apoi accesează: http://localhost:8080 (cu header Host: myapp.local)"
echo ""
echo "4. SAU adaugă în /etc/hosts și folosește port-forward:"
echo "   echo '127.0.0.1 myapp.local' | sudo tee -a /etc/hosts"
echo "   kubectl port-forward -n ingress-nginx svc/ingress-nginx-controller 80:80"
echo ""
echo "5. Verifică dacă alt proces ocupă portul 80:"
echo "   sudo lsof -i :80"

